"""Adiciona campos de contato ao usuario e melhora API de oferta

Revision ID: 3448bf0b9c5d
Revises: 71a0649bca67
Create Date: 2025-09-23 15:11:43.047419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3448bf0b9c5d'
down_revision = '71a0649bca67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('horarios_disponiveis', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('info_contato', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('info_contato')
        batch_op.drop_column('horarios_disponiveis')
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
