"""Adiciona criador_id a grupos e logica de permissoes

Revision ID: 6367e0cd3b1f
Revises: 3448bf0b9c5d
Create Date: 2025-09-24 19:27:43.552629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6367e0cd3b1f'
down_revision = '3448bf0b9c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criador_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'usuarios', ['criador_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('criador_id')

    # ### end Alembic commands ###
