"""Especifica foreign keys no modelo Solicitacao para resolver ambiguidade

Revision ID: 71a0649bca67
Revises: 9a620dc27222
Create Date: 2025-09-23 13:26:11.500457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a0649bca67'
down_revision = '9a620dc27222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.Column('avaliador_id', sa.Integer(), nullable=False),
    sa.Column('avaliado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['avaliado_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['avaliador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atendido_por_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['atendido_por_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('atendido_por_id')

    op.drop_table('avaliacoes')
    # ### end Alembic commands ###
