"""Adiciona modelos de Conversa e Mensagem para o chat

Revision ID: 9a620dc27222
Revises: e3e8dfa7f757
Create Date: 2025-09-23 12:08:38.416317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a620dc27222'
down_revision = 'e3e8dfa7f757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solicitacao_id')
    )
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('conversa_id', sa.Integer(), nullable=False),
    sa.Column('remetente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversas.id'], ),
    sa.ForeignKeyConstraint(['remetente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagens')
    op.drop_table('conversas')
    # ### end Alembic commands ###
